
services:
  lab-ims-frontend:
    container_name: lab-ims-frontend
    restart: always
    image: node:22
    ports:
      - 4006:4006
    environment:
      - PORT=4006
      - NODE_ENV=production
      - BACKEND_URL=http://72.61.116.31:4005
      - BACKEND_HOST=72.61.116.31
    env_file:
      - .env.local
    volumes:
      - ./:/usr/src/lab-ims-frontend
      - /usr/src/lab-ims-frontend/node_modules
      - /usr/src/lab-ims-frontend/.next
    working_dir: /usr/src/lab-ims-frontend
    networks:
      - lab-ims-net
    command: bash -c "NODE_ENV=development yarn install --frozen-lockfile --network-timeout 600000 && yarn build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static && node .next/standalone/server.js"

networks:
  lab-ims-net:
    name: lab-ims-net
    driver: bridge